### ISSUE TITLE
Testing with macOS Mojave and GCC gcc-8

### ISSUE THREAD

**Issue by mansoure** [epfl-dias/pelago#1]
I am using macOS Mojave and GCC gcc-8 (Homebrew GCC 8.2.0) 8.2.0. 
I did `make`. I got the following errors. Please let me know if you have fixes on this issue, or if there are specific prerequisites. 

14 warnings generated.
[ 62%] Building CXX object projects/compiler-rt/lib/tsan/CMakeFiles/clang_rt.tsan_osx_dynamic.dir/rtl/tsan_libdispatch_mac.cc.o
/Users/emansour/elab/systems/github/pelago/src/llvm/projects/compiler-rt/lib/tsan/rtl/tsan_libdispatch_mac.cc:195:27: error: conflicting types for 'dispatch_sync'
DISPATCH_INTERCEPT_SYNC_B(dispatch_sync, false)
                          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/dispatch/queue.h:292:1: note: previous declaration is here
dispatch_sync(dispatch_queue_t queue, DISPATCH_NOESCAPE dispatch_block_t block);
^
/Users/emansour/elab/systems/github/pelago/src/llvm/projects/compiler-rt/lib/tsan/rtl/tsan_libdispatch_mac.cc:196:27: error: conflicting types for
      'dispatch_barrier_sync'
DISPATCH_INTERCEPT_SYNC_B(dispatch_barrier_sync, true)
                          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/dispatch/queue.h:1278:1: note: previous declaration is here
dispatch_barrier_sync(dispatch_queue_t queue,
^
/Users/emansour/elab/systems/github/pelago/src/llvm/projects/compiler-rt/lib/tsan/rtl/tsan_libdispatch_mac.cc:236:24: error: conflicting types for 'dispatch_once'
TSAN_INTERCEPTOR(void, dispatch_once, dispatch_once_t *predicate,
                       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/dispatch/once.h:73:1: note: previous declaration is here
dispatch_once(dispatch_once_t *predicate,
^
/Users/emansour/elab/systems/github/pelago/src/llvm/projects/compiler-rt/lib/tsan/rtl/tsan_libdispatch_mac.cc:446:24: error: conflicting types for 'dispatch_apply'
TSAN_INTERCEPTOR(void, dispatch_apply, size_t iterations,
                       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/dispatch/queue.h:389:1: note: previous declaration is here
dispatch_apply(size_t iterations,
^
/Users/emansour/elab/systems/github/pelago/src/llvm/projects/compiler-rt/lib/tsan/rtl/tsan_libdispatch_mac.cc:490:47: warning: cast from 'const void *' to 'void *'
      drops const qualifier [-Wcast-qual]
    destructor = ^(void) { WRAP(free)((void *)buffer); };
                                              ^
/Users/emansour/elab/systems/github/pelago/src/llvm/projects/compiler-rt/lib/tsan/rtl/tsan_libdispatch_mac.cc:492:49: warning: cast from 'const void *' to 'void *'
      drops const qualifier [-Wcast-qual]
    destructor = ^(void) { WRAP(munmap)((void *)buffer, size); };
                                                ^
2 warnings and 4 errors generated.
make[5]: *** [projects/compiler-rt/lib/tsan/CMakeFiles/clang_rt.tsan_osx_dynamic.dir/rtl/tsan_libdispatch_mac.cc.o] Error 1
make[4]: *** [projects/compiler-rt/lib/tsan/CMakeFiles/clang_rt.tsan_osx_dynamic.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [do-build-llvm] Error 2
make[1]: *** [llvm.build_done] Error 2
make: *** [postgres.configure_done] Error 2

**Comment by sambuc** [comment]
Hello,


Yes, there are specific requirements, as listed in the README file, mainly we have only tested our software on Ubuntu 16.04, and to a lesser extend on some versions of RedHat.

Second, you might have a better chance building clang with the default MacOS compiler, which is also clang, instead of using GCC.

At this point we have not yet plans, nor ressources, to have extensive cross-platform support.


Kind regards

**Comment by mansoure** [comment]
Thank you very much! I will use Docker with Ubuntu 16.04.

Best Regards,

Essam
